repos:
-   repo: local
    hooks:
    -   id: yapf
        name: yapf
        entry: poetry run yapf -i -r --style=.style.yapf pyxxl
        language: system
        types: [python]
    -   id: pylint
        name: pylint
        entry: poetry run pylint --rcfile=pylintrc
        language: system
        types: [python]